repos:
  - repo: local
    hooks:
      - id: make-check
        name: Run "make pre-commit" hook
        entry: make pre-commit
        language: system
        pass_filenames: false
        stages: [commit] 