
title = "CSV Source Files Configuration"

[file.claim_raw]
# example file: YouTube_SomeBrandName_M_20230601_claim_raw_v1-1.csv.tar.gz
is_enabled = true
storage_folder_name = "caravan/claim_raw"
table_name = "claim_raw"
select_file_name_base = "claim_raw"
exclude_file_name_base = "adj_claim_raw"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})' 
regex_group_names = ["content_owner", "file_date_key"]
# file_date_key is special and it will be converted to a eom report_date_key when found (for now)
table_append_or_replace = "append"
# TODO MAYBE: 
# is_skip_first_row = true
# file_name_base_is_case_sensitive = false


[file.adj_claim_raw]
is_enabled = true
storage_folder_name = "caravan/adj_claim_raw"
table_name = "adj_claim_raw"
select_file_name_base = "ADJ_claim_raw" # case sensitive!
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]
table_append_or_replace = "append"

# [source.video_raw]
# file_name_base = "video_raw"
# destination_table = "video_raw"
# is_enabled = false
# append_or_replace = "append"
# regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
# regex_group_names = ["content_owner", "file_date_key"]

# [source.red_rawdata_asset]
# file_name_base = "red_rawdata_asset"
# destination_table = "red_rawdata_asset"
# is_enabled = false
# append_or_replace = "append"
# regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
# regex_group_names = ["content_owner", "file_date_key"]

# [source.red_music_rawdata_asset]
# file_name_base = "red_music_rawdata_asset"
# destination_table = "red_music_rawdata_asset"
# is_enabled = false
# append_or_replace = "append"
# regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
# regex_group_names = ["content_owner", "file_date_key"]

# [source.monthly_shorts_non_music_ads_video_summary]
# file_name_base = "monthly_shorts_non_music_ads_video_summary"
# destination_table = "monthly_shorts_non_music_ads_video_summary"
# is_enabled = false
# append_or_replace = "append"
# regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
# regex_group_names = ["content_owner", "file_date_key"]

# [source.monthly_shorts_non_music_subscription_video_summary]
# file_name_base = "monthly_shorts_non_music_subscription_video_summary"
# destination_table = "monthly_shorts_non_music_subscription_video_summary"
# is_enabled = false
# append_or_replace = "append"
# regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
# regex_group_names = ["content_owner", "file_date_key"]

# [source.video_report]
# file_name_base = "video_report"
# destination_table = "video_report"
# is_enabled = false
# append_or_replace = "replace"
