[tool.poetry]
name = "datawagon"
version = "0.1.0"
description = "Automated loading of YouTube Analytics files into a PostgreSQL database"
authors = ["JM <jtmcn.dev@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "datawagon"}]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
tabulate = "^0.9.0"
psycopg2-binary = "^2.9.6"
python-dotenv = "^1.0.0"
pandas = "^2.0.2"
sqlalchemy = "^2.0.17"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
mypy = "^1.4.1"
flake8 = "^6.0.0"
pydantic = "^1.10.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
