
[project]
name = "datawagon"
version = "0.1.0"
description = "Automated loading of YouTube Analytics files into a PostgreSQL database"
authors = [
    {name = "JM", email = "jtmcn.dev@gmail.com"},
]
dependencies = [
    "click>=8.1.3",
    "psycopg2-binary>=2.9.6",
    "python-dotenv>=1.0.0",
    "pandas>=2.0.2",
    "sqlalchemy>=2.0.16",
    "tabulate>=0.9.0",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.3.2",
]
code = [
    "mypy>=1.4.0",
    "flake8>=6.0.0",
]
