[tool.poetry]
name = "datawagon"
version = "0.1.0"
description = "Automated loading of YouTube Analytics files into a PostgreSQL database"
authors = ["JM <jtmcn.dev@gmail.com>"]
license = "MIT"
# readme = "README.md"
packages = [{include = "datawagon"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
click = "^8.1.3"
tabulate = "^0.9.0"
python-dotenv = "^1.0.0"
pandas = "^2.0.2"
sqlalchemy = "^2.0.17"
psycopg2 = "^2.9.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
mypy = "^1.4.1"
flake8 = "^6.0.0"
pydantic = "^1.10.9"
isort = "^5.12.0"
black = "^23.3.0"
pyinstaller = "^5.13.0"
pytest-cov = "^4.1.0"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
