
title = "CSV Source Files to be loaded into the database"

[source.claim_raw]
# example file: YouTube_SomeBrandName_M_20230601_claim_raw_v1-1.csv.tar.gz
is_enabled = false
file_name_base = "claim_raw" 
exclude_file_name_base = "adj_claim_raw"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})' 
regex_group_names = ["content_owner", "file_date_key"]
# file_date_key is special and it will be converted to a eom report_date_key when found
destination_table = "claim_raw"
append_or_replace = "append"
# TODO MAYBE: 
# is_skip_first_row = true
# file_name_base_is_case_sensitive = false

[source.adj_claim_raw]
file_name_base = "adj_claim_raw"
destination_table = "adj_claim_raw"
is_enabled = true
append_or_replace = "append"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[source.video_raw]
file_name_base = "video_raw"
destination_table = "video_raw"
is_enabled = false
append_or_replace = "append"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[source.red_rawdata_asset]
file_name_base = "red_rawdata_asset"
destination_table = "red_rawdata_asset"
is_enabled = false
append_or_replace = "append"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[source.red_music_rawdata_asset]
file_name_base = "red_music_rawdata_asset"
destination_table = "red_music_rawdata_asset"
is_enabled = false
append_or_replace = "append"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[source.monthly_shorts_non_music_ads_video_summary]
file_name_base = "monthly_shorts_non_music_ads_video_summary"
destination_table = "monthly_shorts_non_music_ads_video_summary"
is_enabled = false
append_or_replace = "append"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[source.monthly_shorts_non_music_subscription_video_summary]
file_name_base = "monthly_shorts_non_music_subscription_video_summary"
destination_table = "monthly_shorts_non_music_subscription_video_summary"
is_enabled = false
append_or_replace = "append"
regex_pattern = 'YouTube_(.+)_M_(\d{8}|\d{6})'
regex_group_names = ["content_owner", "file_date_key"]

[source.video_report]
file_name_base = "video_report"
destination_table = "video_report"
is_enabled = false
append_or_replace = "replace"
